### ISSUE TITLE
What's in between PrintTemplate is hidden

### ISSUE THREAD

**Issue by mfgabriel92** [captray/react-print#2]
I have a page with several information to fill up and I wanna print the final summary that's shown. These are tabs that are changed as I proceed. But when I surround the component responsible for the summary with `PrintTemplate`, all the content disappears.

```javascript
// ...
import PrintTemplate from 'react-print'

class Summary extends Component {
  render() {
    // ...
    return (
      </div>
        <PrintTemplate> 
           // ...
        </PrintTemplate>
      </div>
    )
  }
}
```

It's a big component which data is what I've previously typed, all together.

**Comment by captray** [comment]
The idea is that you would put what you want to show inside of the <PrintTemplate>, and everything else that isn't inside of that would be hidden. You may want to look at the CSS and the example on the homepage. Specifically the following: 

<div id="react-no-print"></div> 
<div id="print-mount"></div> 

Using the IDs above on the elements you're wanting to hide versus what you want to print. The whole point of this is to print something different than what is statically on your page.

I hope this makes sense, if it doesn't, I may need to understand what you're trying to do better. 

If you're expecting to place components inside of the print template instead of simply JSX, that may actually be a bug, since I've never used it that way.

**Comment by csavage1994** [comment]
If the code you have is copied and pasted from your app, you have 2 closing `</div>` tags instead of an opening and closing one as well

**Comment by captray** [comment]
@csavage1994 is correct. I'll be closing this. If you're still having issues after adjusting your code, we can reopen it.
